version: "3.8"

services:
  fitnesblog:
    image: fitnesblog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80" # Dış dünyadan 80 → Container içinde 80
      - "8080:8080" # Dış dünyadan 8080 → Container içinde 8080
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx konfigürasyonunu bağla
    networks:
      - default
