services:
  fitnesblog:
    image: fitnesblog
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fitnesblog.rule=Host(`n0o04kko44gcw4ocksog884w.2.59.117.162.sslip.io`)
      - traefik.http.services.fitnesblog.loadbalancer.server.port=8080
      - traefik.http.middlewares.redirect-to-8080.redirectscheme.scheme=http
      - traefik.http.middlewares.redirect-to-8080.redirectscheme.port=8080
      - traefik.http.routers.fitnesblog.middlewares=redirect-to-8080
      - traefik.http.routers.fitnesblog.entrypoints=web
      - traefik.http.routers.fitnesblog.rule=Host(`n0o04kko44gcw4ocksog884w.2.59.117.162.sslip.io`)
      - traefik.http.services.fitnesblog.loadbalancer.server.port=8080
