services:
  fitnesblog:
    image: fitnesblog
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"
    restart: unless-stopped
