version: "3.8"

services:
  fitnesblog:
    image: fitnesblog
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8080:80" # Dışarıdan 8080'e, container içinde 80'e yönlendiriyoruz.
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fitnesblog.rule=Host(`n0o04kko44gcw4ocksog884w.2.59.117.162.sslip.io`)
      - traefik.http.services.fitnesblog.loadbalancer.server.port=8080
